import React, { useContext, useState,useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { Store } from '../utils/Store';
import type {product} from "../utils/data"





export default function Layout({
	children,
	title,
}: {
	children: React.ReactNode;
	title?: string;
}) {
	const [tag,settag]= useState(0)
	const { state } = useContext(Store);
	const { cart } = state;
	useEffect(()=>{
		let e=0
		//TODO solve this 
		//@ts-ignore
		cart.cartItems.map((item:product)=>{e=e+item?.quantity})
		settag(e)
	},[cart])
	return (
		<>
			<Head>
				<title>{title ? title + ' - Gozarche' : 'amazona'}</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex min-h-screen flex-col justify-between">
				<header>
					<nav className="flex h-12 justify-between items-center ph-4 shadow-[0_-5px_10px_0_rgba(0,0,0,0.3)]">
						<Link href="/" passHref>
							<p className="text-lg p-3 bg">Gozarche</p>
						</Link>
						<div className="">
							<Link href="/cart">
								<span className="p-3">
									Cart
									{tag > 0 && (
										<span className="ml-1 rounded-full bg-red-600 px-2 py-1 text-xs font-bold text-white">
											{cart.cartItems.reduce(
												(a: number, c: any) =>
													a + c.quantity,
												0
											)}
										</span>
									)}
								</span>
							</Link>
							<Link href="/login">
								<span className="p-3">Login</span>
							</Link>
						</div>
					</nav>
				</header>
				<main className="container m-auto mt-4 ">{children}</main>
				<footer className="flex ph-4 justify-center  items-center shadow-[0_5px_10px_0_rgba(0,0,0,0.3)]">
					footer
				</footer>
			</div>
		</>
	);
}
